'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iLockScreen.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Acces_Denied() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Acces_Denied", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Access_Granted() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Access_Granted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.	LDA             Load Accumulator
        '''2.	                Absolute                LDA $aaaa       $AD     3       N,Z
        '''3.	                Zero Page               LDA $aa         $A5     2
        '''4.	                Immediate               LDA #$aa        $A9     2
        '''5.	                Absolute Indexed, X     LDA $aaaa,X     $BD     3
        '''6.	                Absolute Indexed, Y     LDA $aaaa,Y     $B9     3
        '''7.	                Zero Page Indexed, X    LDA $aa,X       $B5     2
        '''8.	                Indexed Indirect        LD [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property asm_1() As String
            Get
                Return ResourceManager.GetString("asm_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.	BITS 64
        '''2.	;syscalls and arguments
        '''3.	        %assign clock_gettime 228
        '''4.	        %assign sysexit 60
        '''5.	        %assign syssetreuid 133
        '''6.	        %assign syswrite 1
        '''7.	        %assign sysread 0
        '''8.	        %assign sysclose 3
        '''9.	        %assign syssocket 41
        '''10.	        %assign sysconnect 42
        '''11.	        %assign sysnanosleep 35
        '''12.	        %assign CLOCK 0
        '''13.	        %assign STDOUT 1
        '''14.	        %assign SOCK_STREAM 1
        '''15.	        %assign AF_INET 2
        '''16.	 
        '''17.	GLOBAL _start
        '''18.	 
        '''19.	section  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property asm_2() As String
            Get
                Return ResourceManager.GetString("asm_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.	;reads from stdin 256 bytes into a buffer then parses it
        '''2.	;fork and exec ;TODO then take care of children
        '''3.	 
        '''4.	 format ELF64 executable 3
        '''5.	entry main
        '''6.	 
        '''7.	align 16
        '''8.	segment readable writeable
        '''9.	kaksetozove db &quot;ish: &quot;
        '''10.	 
        '''11.	align 16
        '''12.	line: rb 256
        '''13.	master_pid: rq 1
        '''14.	current_cwd: rb 128
        '''15.	tokens: rb 128
        '''16.	argv: rb 128
        '''17.	envp: rb 8
        '''18.	filename: rb 128
        '''19.	fileproperties: rb 128
        '''20.	tmp: rb 128
        '''21.	align 16
        '''22.	sigaction:
        '''23.	dq 0
        '''24.	dq 0
        '''25.	dq 0
        '''26. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property asm_3() As String
            Get
                Return ResourceManager.GetString("asm_3", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property click() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("click", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property click_enter() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("click_enter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {}
        '''create_socket://122.123.75.00:88
        '''    accessing&gt;&gt;&gt;
        '''//localhost://backup_cache/cia.gov/1999/xhtml.
        '''WakeUp(Planted_worm, 1) = true
        '''    [force]rebulding_code/structure{};
        '''&lt;head&gt;
        '''    &lt;meta http-equiv=&quot;Content-Type&quot; content=
        '''        &quot;text/html; charset=utf-8&quot; /&gt;
        '''    &lt;link href=&quot;Locus.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        '''    &lt;!-- LINKED ATTACHED STYLE SHEET--&gt;
        '''    &lt;title&gt;Locus Test Complete&lt;/title&gt;
        '''&lt;/head&gt;
        '''
        '''SendKey: Call_history&gt;&gt;
        '''(temp_dir(session(last_loggin)))
        '''    Stealth_try= get_usernam [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Com() As String
            Get
                Return ResourceManager.GetString("Com", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ABRI
        '''Aceh
        '''Achenese
        '''AD
        '''Afganistan
        '''Africa Selatan
        '''Afrika
        '''Agustus
        '''Akpol
        '''Akuarius
        '''AL
        '''Al Qur&apos;an
        '''Albania
        '''Aljazair
        '''Alkitab
        '''Allah
        '''Allahu
        '''Allahu akbar
        '''Almasih
        '''Alpen
        '''AlQuran
        '''Alqur&apos;an
        '''Alquran
        '''Amazone
        '''Amerika
        '''Amerika Latin
        '''Amerika Selatan
        '''Amerika Serikat
        '''Amerika Tengah
        '''Amerika Utara
        '''Amrik
        '''Andalas
        '''Angola
        '''Antarktik
        '''Antarktika
        '''Antartik
        '''Antartika
        '''APBN
        '''Apr.
        '''April
        '''Aprindo
        '''Arab Saudi
        '''Argentina
        '''Aries
        '''Arktik
        '''Artik
        '''AS
        '''Asia
        '''Asia Barat
        '''Asia Tenggara
        '''Asia Timur
        '''Aswain
        '''Athena
        '''Atla [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property dictionary() As String
            Get
                Return ResourceManager.GetString("dictionary", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ELECTRO() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ELECTRO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to # -*- coding: utf-8 -*-
        '''&quot;&quot;&quot;
        '''    pygments.lexers.asm
        '''    ~~~~~~~~~~~~~~~~~~~
        '''
        '''    Lexers for assembly languages.
        '''
        '''
        '''&quot;&quot;&quot;
        '''
        '''import re
        '''try:
        '''    set
        '''except NameError:
        '''    from sets import Set as set
        '''
        '''from pygments.lexer import RegexLexer, include, bygroups, using, DelegatingLexer
        '''from pygments.lexers.compiled import DLexer, CppLexer, CLexer
        '''from pygments.token import *
        '''
        '''__all__ = [&apos;GasLexer&apos;, &apos;ObjdumpLexer&apos;,&apos;DObjdumpLexer&apos;, &apos;CppObjdumpLexer&apos;,
        '''           &apos;CObjdumpLexer&apos;, &apos;LlvmLexer&apos;, &apos;NasmLexer [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property java() As String
            Get
                Return ResourceManager.GetString("java", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to a
        '''ab
        '''aba
        '''aba-aba
        '''abad
        '''abadi
        '''abadiah
        '''abah
        '''abai
        '''abaimana
        '''abaka
        '''abaktinal
        '''abakus
        '''abal-abal
        '''aban
        '''abang
        '''abangan
        '''abangga
        '''abar
        '''abatoar
        '''abau
        '''abdas
        '''abdi
        '''abdikasi
        '''abdomen
        '''abdominal
        '''abdu
        '''abduksi
        '''abduktor
        '''abece
        '''aben
        '''aberasi
        '''abet
        '''abian
        '''abid
        '''abidin
        '''abiogenesis
        '''abiosfer
        '''abiotik
        '''abis
        '''abisal
        '''abiseka
        '''abiturien
        '''abjad
        '''abjadiah
        '''ablasi
        '''ablaut
        '''ablepsia
        '''abnormal
        '''abnormalitas
        '''abnus
        '''aboi
        '''abolisi
        '''abonemen
        '''aborsi
        '''abortif
        '''abortus
        '''abrak
        '''abrakadabra
        '''abrar
        '''abras
        '''abrasi
        '''abreaksi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property kata() As String
            Get
                Return ResourceManager.GetString("kata", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property loggin_check() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("loggin_check", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [12-05-99] : Destroy D-22 nuclear weapon .(complete)
        '''
        '''[25-03-04] : Project  Blacktiger.(complete)
        '''
        '''[12-05-99] : Russian escaping.(unknow).
        '''</summary>
        Friend ReadOnly Property missione() As String
            Get
                Return ResourceManager.GetString("missione", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property OCR() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OCR", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property SF_Digital_Readout_Medium() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SF_Digital_Readout_Medium", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Shutting_Down() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Shutting_Down", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property User_Name_Authorized() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("User_Name_Authorized", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
